<?php

namespace OS\SarpgBundle\Repository;

/**
 * ucrpgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ucrpgRepository extends \Doctrine\ORM\EntityRepository
{
}
