<?php

namespace OS\SarpgBundle\Repository;

/**
 * voteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class voteRepository extends \Doctrine\ORM\EntityRepository
{
}
